#Plugin This Create 4 Agustus 2021
#Real Author HaykalPRO
#Don't Change This Author
name: HealFeedUI
author: HaykalPRO
main: healfeedui\Main
api: 3.0.0
version: 1.0.0

commands:
  hfui:
    description: §aHealFeed With UI!
    permission: use.hfui

permissions:
  use.hfui:
    description: "/hfui"
