#Author HaykalPRO
#Don't Change This Author
MSG-HEAL: "§f[§aHealFeedUI§f] Health You Full"
MSG FEED: "§f[§aHealFeedUI§f] FEED You Full"
TITLE-UI: "§l§gHEALFEEDUI"
CONTENT-UI: "§fHealFeedUI By HaykalPRO"
BTN-HEAL: "Heal"
BTN-FEED: "Feed"